import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const dmSans = localFont({
  variable: "--font-dm-sans",
  display: "swap",
  src: [
    {
      path: "../public/font/static/DMSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/static/DMSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/font/static/DMSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/font/static/DMSans-Italic.ttf",
      weight: "400",
      style: "italic",
    },
  ],
});

const geistMono = localFont({
  variable: "--font-geist-mono",
  display: "swap",
  src: [
    {
      path: "../public/font/static/DMSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
